# Generated by Django 3.0.6 on 2020-07-08 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiryid', models.IntegerField()),
                ('studentname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=50)),
                ('collegename', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('enquirydate', models.DateField(default=datetime.date(2020, 7, 8))),
                ('followup_date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Call_back'), ('2', 'Admitted'), ('3', 'Cancel')], max_length=20)),
            ],
        ),
    ]
