# Generated by Django 3.0.6 on 2020-07-08 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studentenquiry', '0002_auto_20200708_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='id',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiryid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
