# Generated by Django 3.0.6 on 2020-07-14 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentenquiry', '0003_auto_20200708_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('batch_date', models.DateField(default=datetime.date(2020, 7, 14))),
                ('batch_status', models.CharField(choices=[('1', 'Yet to begin'), ('2', 'Ongoing'), ('3', 'Completed')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquirydate',
            field=models.DateField(default=datetime.date(2020, 7, 14)),
        ),
    ]
