# Generated by Django 3.0.6 on 2020-07-15 18:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentenquiry', '0005_auto_20200715_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_fees',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_date',
            field=models.DateField(default=datetime.date(2020, 7, 16)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentenquiry.Course'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquirydate',
            field=models.DateField(default=datetime.date(2020, 7, 16)),
        ),
    ]
