# Generated by Django 3.0.6 on 2020-07-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentenquiry', '0006_auto_20200716_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_fees',
            field=models.CharField(max_length=50),
        ),
    ]
