# Generated by Django 3.0.6 on 2020-07-16 06:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentenquiry', '0007_auto_20200716_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50, unique=True)),
                ('enquiryid', models.CharField(max_length=50)),
                ('coursefees', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2020, 7, 16))),
                ('batchcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentenquiry.Batch')),
            ],
        ),
    ]
