# Generated by Django 3.0.6 on 2020-07-16 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentenquiry', '0008_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField(default=datetime.date(2020, 7, 16))),
                ('enquiryid', models.CharField(max_length=50)),
            ],
        ),
    ]
