# Generated by Django 3.0.6 on 2020-07-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentenquiry', '0010_auto_20200720_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_fees',
        ),
    ]
