# Generated by Django 3.0.6 on 2020-07-26 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentenquiry', '0011_remove_course_course_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counsellor_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='studentname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='source',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='batch',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admission',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 26)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_date',
            field=models.DateField(default=datetime.date(2020, 7, 26)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquirydate',
            field=models.DateField(default=datetime.date(2020, 7, 26)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.date(2020, 7, 26)),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='counsellor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='studentenquiry.Counsellor'),
            preserve_default=False,
        ),
    ]
